### ISSUE TITLE
Mitigate Selling/Buying confusion

### ISSUE THREAD

**Issue by nakamotoms** [vexl-it/vexl#34] opened 2022-09-17 21:46 UTC

**Comment by prusnak** [comment] 2022-09-18 20:32
I think the correct solution is to add description to the top part of the "Add Offer" screen.

It could look like this:

Buy:
```
$ → ₿
Selling Fiat
Buying Bitcoin
```

Sell:
```
₿ → $
Selling Bitcoin
Buying Fiat
```

**Comment by leomira** [comment] 2022-09-18 21:15
I think the main problem is not the "Add offer" screen, but the marketplace terminology itself. 

We can partly solve it by implementing #35 .

**Comment by prusnak** [comment] 2022-09-18 21:24
Agreed that unifying the button is the way to go - let's close this as a duplicate of https://github.com/vexl-it/vexl/issues/35

**Closed by prusnak** 2022-09-18 21:24 UTC
Labels: ios, android, improvement
