### ISSUE TITLE
Offers persist after contact removed

### ISSUE THREAD

**Issue by elkimek** [vexl-it/vexl#116] opened 2022-10-18 08:58 UTC
Hi, it's been 24 hours since I removed few contacts (SIM ones) but all related offers are still listed. What changed is that those offers now show no common friends.

Android 13
Calyx OS 4.2.3

**Comment by leomira** [comment] 2022-10-18 10:15
related to #36

**Comment by slush0** [comment] 2022-10-18 21:29
It is literally duplicate of #36. Closing.

**Closed by slush0** 2022-10-18 21:29 UTC

**Comment by slush0** [comment] 2022-10-18 21:30
It will be fixed by coincidence in next release, which will force app to reencrypt and reupload all offers once again. So these offers will go away.
