### ISSUE TITLE
Translate button for offers 

### ISSUE THREAD

**Issue by satsdisco** [vexl-it/vexl#906] opened 2024-03-14 11:05 UTC
As Vexl scales and people are moving around, several users have requested a button to translate the content of an offer. 

If the offer is written in Czech/Italian/Greek/English could it be possible to translate the content automatically to the language of their choice? 

It could help to make the app more approachable to users who are traveling and find they have connections in cities where they are traveling. 

Similar to how twitter/x has a translate button on tweets.

**Comment by leomira** [comment] 2024-03-14 19:45
duplicate of #858 

Also on Android, they can use Google Assistant - works pretty well
unfortuntely I don't know how iOS works

**Closed as completed by leomira** 2024-03-14 19:45 UTC
