### ISSUE TITLE
A list of active offers is hidden under the "Create new offer" button

### ISSUE THREAD

**Issue by vbspam** [vexl-it/vexl#5] opened 2022-09-15 16:49 UTC
A list of active offers is hidden under the "Create new offer" button.

**How to reproduce**
1. Create an offer ABC.
2. Try to access the offer ABC.
3. Open the offer list through "Create new offer".

**What happens**
The list of active offers is hidden under the "Create new offer" button.

**Expected behavior**
The list of active offers shall be accessed under a meaningful name or icon.

**Comment by slush0** [comment] 2022-09-17 10:20
Agree, and I propose to leave "Create new offer" in Buy/Sell tabs, but allow displaying my offers in Profile section ("My offers").

**Comment by leomira** [comment] 2022-09-21 20:20
already working on this, this is a duplicate of an issue https://github.com/vexl-it/vexl/issues/35 so I am closing this.

**Closed by leomira** 2022-09-21 20:20 UTC
Labels: ios, android, improvement, UX needed
