### ISSUE TITLE
Displaying FoF offer without common friends

### ISSUE THREAD

**Issue by elkimek** [vexl-it/vexl#109] opened 2022-10-07 10:15 UTC
FYI, probably bug?

![signal-2022-10-07-120637_002](https://user-images.githubusercontent.com/36666630/194530741-bef5c5d3-cc2d-4120-86d4-b0e825daa4b7.png)

**Comment by leomira** [comment] 2022-10-07 10:19
Thanks, this is a duplicate of #50

**Closed by leomira** 2022-10-07 10:19 UTC
